### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by phucplusplus** [haig233/Moecat#5]
I changed all to my website url (all info are correct) and received that error

![New Bitmap Image](https://user-images.githubusercontent.com/20884522/72333306-23dca300-36ee-11ea-8136-b6559db2970d.png)

**Comment by haig233** [comment]
@phucplusplus Hi sir, please make sure you are using 5.6 version of php and have the extension installed correctly

**Comment by phucplusplus** [comment]
> @phucplusplus Hi sir, please make sure you are using 5.6 version of php and have the extension installed correctly

Oh sorry, I missed the OP Cache installation, solved. Thank you sir

**Comment by haig233** [comment]
@phucplusplus OP Cache does not affect the normal operation of the website (IMHO: optional), if you still encounter 500 errors, please switch to the root directory of the website under SSH, run php index.php and provide the returned data to me

**Comment by lbq1121** [comment]
![image](https://user-images.githubusercontent.com/24562314/84096971-d3b40380-aa35-11ea-890f-947b58af57ac.png)
classes/class_cache.php on line 240 報錯了
